### ISSUE TITLE
Java `new` keyword is parsed as an operator not a keyword

### ISSUE THREAD

**Issue by jrmoulton** [tree-sitter/tree-sitter-java#102]
### Problem description
It seems in my nvim config that the `new` keyword in java is categorized the same as an operator instead of a keyword. 
<img width="323" alt="Screen Shot 2022-02-01 at 5 53 28 PM" src="https://user-images.githubusercontent.com/13090441/152076059-edfd5915-cec2-4f86-b7cb-2af635e55e1e.png">

Is there a reason that the new keyword takes the same classification as an operator?

(I'm not sure how to get the expected parse output)

**Comment by maxbrunsfeld** [comment]
You should open this as an issue on [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). They provider their own highlighting queries.
