### ISSUE TITLE
Release and tag a new version

### ISSUE THREAD

**Issue by jirutka** [tree-sitter/tree-sitter-java#107]
Can you please release a new version? The latest one (v0.19.1) doesn’t work with modern nvim-treesitter.

I’m maintainer of the [tree-sitter-java](https://pkgs.alpinelinux.org/packages?name=tree-sitter-java) package in Alpine Linux and I had to update the package to the latest revision in the master branch, instead of using the tagged release, which is not optimal.

**Comment by jirutka** [comment]
@aryx ping

**Comment by aryx** [comment]
What should be the release number? 0.xxx.yyy?

**Comment by jirutka** [comment]
You’ve already bumped version in Cargo.toml to 0.20.0 in [8833939](https://github.com/tree-sitter/tree-sitter-java/commit/88339390aa70ca6784ecac82c34affa456dc6382). So I suppose it should be 0.20.0. However, I’m not maintainer of this project, I don’t know your versioning policy.

**Comment by jirutka** [comment]
You didn’t bump version in [package.json](https://github.com/tree-sitter/tree-sitter-java/blob/master/package.json) and [Makefile](https://github.com/tree-sitter/tree-sitter-java/blob/master/Makefile)!

**Comment by aryx** [comment]
There's been some discussions about it actually recently on the main tree-sitter repo: https://github.com/tree-sitter/tree-sitter/discussions/1768

**Comment by aryx** [comment]
@maxbrunsfeld what do I need to know to make those new release? What is currently automated?
