### ISSUE TITLE
Data types are no longer highlighted

### ISSUE THREAD

**Issue by TheWitheredStriker** [tree-sitter/tree-sitter-java#116]
### Problem description

Java data type keywords are no longer highlighted correctly.

![image](https://user-images.githubusercontent.com/38614982/179397963-06098286-76ae-4024-8706-b10a1201e430.png)

This applies even for void functions.

![image](https://user-images.githubusercontent.com/38614982/179397991-ced120ff-4e00-454e-80b3-1d661f42fe8a.png)

As this is the grammar seemingly used by Linguist, this affects all Java repositories on GitHub.

### Expected parse tree output (optional)

N/A.

### Actual parse tree output (optional)

N/A.

**Comment by TheWitheredStriker** [comment]
Hello? Anyone?

**Comment by xiaoma20082008** [comment]
`this` is also a keyword and is not highlighted

**Comment by amaanq** [comment]
Seems like a potential editor issue (if it is, that's on their queries, not here)
