### ISSUE TITLE
Support records implementing interfaces

### ISSUE THREAD

**Issue by riskygit** [tree-sitter/tree-sitter-java#123]
Self-explanatory image attached. In this specific case, "implements" would be purple and the types would be red.

![image](https://user-images.githubusercontent.com/105889909/189798058-677ffe9e-20d2-43f7-bf96-436d62ef3ff0.png)

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/200936672-d9454d80-8dd7-46fa-bc7d-b4d33ec58ba7.png)

They seem to have added these...

**Comment by ice1000** [comment]
But it may not get released yet
