### ISSUE TITLE
The lines for methods are completely broken

### ISSUE THREAD

**Issue by lyriccoder** [tree-sitter/tree-sitter-java#126]
### Problem description
Tree sitter gives wrong lines number for method declaration (both start and end lines). The lines for methods are completely broken for the give file.

### Expected parse tree output (optional)
| method signature | start line |
| ----------- | ----------- |
| Bytes not() | 91|
| Bytes and() | 100 |
| Bytes or() | 110 |
| Bytes xor() | 120 |
| Bytes shift() | 130 |
| Bytes sshift() | 169 |

etc
### Actual parse tree output (optional)
| method name| method_info|
| ----------- | ----------- |
| not | <Node kind=method_declaration, start_point=(77, 4), end_point=(84, 5)>|
| and | <Node kind=method_declaration, start_point=(86, 4), end_point=(94, 5)>|
| or | <Node kind=method_declaration, start_point=(96, 4), end_point=(104, 5)>|
| xor | <Node kind=method_declaration, start_point=(106, 4), end_point=(114, 5)>|
| shift | <Node kind=method_declaration, start_point=(116, 4), end_point=(153, 5)>|
| asNumber | <Node kind=method_declaration, start_point=(155, 4), end_point=(181, 5)>|
| take | <Node kind=method_declaration, start_point=(183, 4), end_point=(186, 5)>|
| toString | <Node kind=method_declaration, start_point=(188, 4), end_point=(191, 5)>|
| equals | <Node kind=method_declaration, start_point=(193, 4), end_point=(204, 5)>|
| hashCode | <Node kind=method_declaration, start_point=(206, 4), end_point=(209, 5)>|

[BytesOf.zip](https://github.com/tree-sitter/tree-sitter-java/files/9596746/BytesOf.zip)

**Comment by suryakunala** [comment]
Hi,
I have also faced this inconsistency, Do we have any solution to tackle this?
Thanks

**Comment by lyriccoder** [comment]
Hi @suryakunala. Sorry, I don’t have any solution. I just stopped using java-tree-sitter.

**Comment by amaanq** [comment]
Is this a tree-sitter-java or java-tree-sitter bug? If the latter, this isn't the right repo

**Comment by lyriccoder** [comment]
It's tree-sitter-java bug

**Comment by amaanq** [comment]
No, the file itself parses fine, this is a bug for probably https://github.com/serenadeai/java-tree-sitter
