### ISSUE TITLE
A class definition with wrong structure is replaced by ERROR

### ISSUE THREAD

**Issue by AdarWeidman** [tree-sitter/tree-sitter-java#127]
### Problem description
When parsing a badly-written code, I'd expect treesitter to have an error.
For example:
```
public class cl1
{
```
yields a "MISSING" error at the end:
```
program [0, 0] - [4, 0]
  class_declaration [0, 0] - [1, 1]
    modifiers [0, 0] - [0, 6]
    name: identifier [0, 13] - [0, 16]
    body: class_body [1, 0] - [1, 1]
      MISSING } [1, 1] - [1, 1]
```
Which makes sense.

BUT, if we mistakenly write something wrong there - I mistakenly closed the class with the wrong parentheses, ")" instead of "}" -
```
public class cl1
{
)
```
The class_declaration  disappears and is replaced by "ERROR":
```
program [0, 0] - [3, 0]
  ERROR [0, 0] - [2, 1]
    modifiers [0, 0] - [0, 6]
    identifier [0, 13] - [0, 16]
```
Although the modifiers and identifiers are still there, so the system "knows" it's a class, just fails to communicate it.

The same happens in many other incomplete class structure, such as:
```
public class cl1
{
a = 3
```
But when adding a semi-colon, the class_declaration appears back.

I would expect to have the ERROR (or MISSING) in the bottom of the tree, and keep the class_declaration above, even possibly also have body.

**Comment by amaanq** [comment]
I think this is a limitation of how tree-sitter's error recovery works. The behavior you're seeing is related to the "missing" token insertion tree-sitter tries when it encounters erroneous code. When the rest of the code parses okay (in your example, `a = 3;`), tree-sitter will try to insert a token at the end of the erroneous code part, and if that reduces successfully to a valid symbol, it will choose that. However, when you omit the semi, tree-sitter would have to insert *two* tokens to produce the class declaration, which it won't do. 

Similarly, in your parenthesis example, tree-sitter is dealing with an incorrect token following the opening brace, and so missing token insertion wouldn't help here. In this case, token-replacement might be a good idea, and maybe only done when at the replacement and replaced are of the same length...but this idea/issue should be filed & explored upstream, not here, so I'll close this out.
