### ISSUE TITLE
Extend comments to differentiate between regular and JavaDoc comment blocks

### ISSUE THREAD

**Issue by dabico** [tree-sitter/tree-sitter-java#132]
More of a question rather than an actual problem. I wanted to create an extension to this grammar so that JavaDoc comments would be recognized separately from plain block comments. Now since my experience with writing a `tree-sitter` grammar is limited, I took it upon myself to base this extension on the [pull request](https://github.com/tree-sitter/tree-sitter-java/commit/a24ae7d16de3517bff243a87d087d0b4877a65c5) that introduced the distinction between line and block comments. Looking at the changes, it seemed easy enough to do. Following the additions of a `javadoc_comment` grammar rule, I regenerated the parser.

I use the 0.20 version of `tree-sitter` through a [custom-made Java wrapper](https://github.com/seart-group/java-tree-sitter). I wanted to see if my grammar extension would work but sadly it does not, returning a null pointer when attempting to parse a source string.

My questions are:
- I just made additions to the grammar based on the changes made by the linked PR. Is there other stuff I need to take into consideration for my particular problem?
- Is there an official step-by-step guide on making changes to the grammar? If so, does this also include instructions on how to test them?

---

For reference, I made the following changes:

I extended the `comment` rule of `grammar.json` to include `javadoc_comment` as a member:
```json
    "comment": {
      "type": "CHOICE",
      "members": [
        {
          "type": "SYMBOL",
          "name": "line_comment"
        },
        {
          "type": "SYMBOL",
          "name": "block_comment"
        },
        {
          "type": "SYMBOL",
          "name": "javadoc_comment"
        }
      ]
    }
```

As well as the `extras`:
```json
  "extras": [
    {
      "type": "SYMBOL",
      "name": "line_comment"
    },
    {
      "type": "SYMBOL",
      "name": "block_comment"
    },
    {
      "type": "SYMBOL",
      "name": "javadoc_comment"
    },
    {
      "type": "PATTERN",
      "value": "\\s"
    }
  ]
```

The rule for this member is:
```json
    "javadoc_comment": {
      "type": "TOKEN",
      "content": {
        "type": "PREC",
        "value": 0,
        "content": {
          "type": "SEQ",
          "members": [
            {
              "type": "STRING",
              "value": "/**"
            },
            {
              "type": "PATTERN",
              "value": "[^*]*\\*+([^/*][^*]*\\*+)*"
            },
            {
              "type": "STRING",
              "value": "/"
            }
          ]
        }
      }
    }
```

I made similar changes in `grammar.js`:

```javascript
...

module.exports = grammar({
  name: 'java',

  extras: $ => [
    $.line_comment,
    $.block_comment,
    $.javadoc_comment,
    /\s/
  ],

...

    // http://stackoverflow.com/questions/13014947/regex-to-match-a-c-style-multiline-comment/36328890#36328890
    comment: $ => choice(
      $.line_comment,
      $.block_comment,
      $.javadoc_comment,
    ),

    line_comment: $ => token(prec(PREC.COMMENT, seq('//', /[^\n]*/))),

    block_comment: $ => token(prec(PREC.COMMENT,
      seq(
        '/*',
        /[^*]*\*+([^/*][^*]*\*+)*/,
        '/'
      )
    )),

    javadoc_comment: $ => token(prec(PREC.COMMENT,
      seq(
        '/**',
        /[^*]*\*+([^/*][^*]*\*+)*/,
        '/'
      )
    )),
  }
});
```

And last but not least, I added `javadoc_comment` entries within `node_types.json`.

**Comment by raghav-deepsource** [comment]
Nice to see another attempt at it. I got stuck while attempting to correctly differentiate the two types of block comments. 

Regarding testing, you will need to add new scenarios to the local tests, like in [this](https://github.com/tree-sitter/tree-sitter-java/commit/a24ae7d16de3517bff243a87d087d0b4877a65c5#diff-5582ea47eae7370774d90f55218052579b06c8a5f758bb8fa3e7dce9a5b3cf9f) file. Make sure to add test cases that you think can confuse the grammar, in the format of all the other examples. Then, (I forget the command) you should be able to run tests, and any mistakes or incongruities will be pointed out.

**Comment by raghav-deepsource** [comment]
also, I believe you don't need to manually edit node-types.json.

**Comment by raghav-deepsource** [comment]
You should try a different approach here. Clone this repo separately and set it up, apply your changes only to grammar.js, then generate the parser and run tests. That would be the ideal approach. Following that, you could update the submodule for tree sitter java to the latest version in your java bindings.

**Comment by dabico** [comment]
Hi Raghav, thank you for the pointers.

> also, I believe you don't need to manually edit node-types.json.

You are indeed correct. I just now realized I only need to edit the `grammar.js` file. Everything else will be created/updated through `tree-sitter generate`. What I have done is the following:

1. Declared a `documentation_comment` in `extras`:
	```javascript
  	extras: $ => [
    	$.line_comment,
    	$.block_comment,
    	$.documentation_comment,
    	/\s/
  	],
	```
2. Added a new rule for `documentation_comment` similar to the one I posted above:
	```javascript
    documentation_comment: $ => token(prec(PREC.COMMENT,
      seq(
        '/**',
        /[^*]*\*+([^/*][^*]*\*+)*/,
        '/'
      )
    )),
	```
3. Added a conflict entry for `block_comment` and `documentation_comment`:
	```javascript
  	conflicts: $ => [
	    // other conflicts here...
    	[$.documentation_comment, $.block_comment],
  	],
	```

> Regarding testing, you will need to add new scenarios to the local tests, like in [this](https://github.com/tree-sitter/tree-sitter-java/commit/a24ae7d16de3517bff243a87d087d0b4877a65c5#diff-5582ea47eae7370774d90f55218052579b06c8a5f758bb8fa3e7dce9a5b3cf9f) file.

I extended the existing `comment` unit test of `comments.txt` as follows:
```
=======
comment
=======

// This is a comment
/* This is also a comment */
/* this comment /* // /** ends here: */
/**/
/** This is a documentation comment */
/* * This is a block comment, but someone was confused :( */

a /* dkjfhsdf + */ + b; /* ***** */

---

(program 
  (line_comment) 
  (block_comment) 
  (block_comment) 
  (block_comment)
  (documentation_comment)
  (block_comment)
  (expression_statement 
    (binary_expression 
      (identifier) 
      (block_comment) 
      (identifier))) 
  (block_comment))
```

While this does seem to correctly handle the new comments at lines 5 and 6, it does break the existing one at line 4, interpreting it as a `documentation_comment` instead of the desired `block_comment`. I'll refine the rule some more to see if I can fix this breaking change.

> Following that, you could update the submodule for tree sitter java to the latest version in your java bindings.

Now here is where I get confused again, mainly with the ABI. I noticed in `parser.c`, the language version gets incremented to 14. Since I'm using `tree-sitter` 0.20.0, the `TREE_SITTER_LANGUAGE_VERSION` and `TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION` are currently set to 13. The reason I bring this up is because I suspect that these version mismatches are preventing me from using the newly generated parser. Any attempt to construct a tree from source code leads to a segfault. I suspect that the root cause of this error is the fact that the ABI version defined in `api.h` of `tree-sitter` does not match the one in `parser.c` of `tree-sitter-java`. Do you know what I should do regarding the versioning?

Many thanks

**Comment by amaanq** [comment]
This should be done with queries
