### ISSUE TITLE
Variable declaration with scoped generic type parsed as binary expression

### ISSUE THREAD

**Issue by ahumenberger** [tree-sitter/tree-sitter-java#138]
### Problem description

The variable declaration `util.List<X> x = null;` gets parsed as nested binary expressions with operators `<`, `>` and `=`, but it should be a "local variable declaration".
This worked with v0.20.0 but does not anymore with v0.20.1. Also, it works if the type is not scoped, e.g. `List<x> x = null;`.

```java
class X {
	void foo() {
    	util.List<X> x = null;
    }
}
```

**Comment by ahumenberger** [comment]
`git bisect` tells me that b042baa283d4e840361fd90d69f751606d42166c introduces the problem.

**Comment by aryx** [comment]
the relevant change to the grammar must be this then: https://github.com/tree-sitter/tree-sitter-java/pull/125
