### ISSUE TITLE
Binary expression with parenthesized operand and bitwise "and" is parsed as cast expression

### ISSUE THREAD

**Issue by ahumenberger** [tree-sitter/tree-sitter-java#142]
```
(r & m) + i;
```

gets parsed as

```
(program [0, 0] - [1, 0]
  (expression_statement [0, 0] - [0, 12]
    (cast_expression [0, 0] - [0, 11]
      type: (type_identifier [0, 1] - [0, 2])
      type: (type_identifier [0, 5] - [0, 6])
      value: (unary_expression [0, 8] - [0, 11]
        operand: (identifier [0, 10] - [0, 11])))))
```

Other operators than `&` seem to work. Also without the `+ i` it works.

**Comment by zimmski** [comment]
@ahumenberger is this something we need to fix? Which repository is this on?

**Comment by ahumenberger** [comment]
@zimmski E.g. `java/util` and `java/math` contain such expressions. https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/math/BigInteger.java#L655
