### ISSUE TITLE
ASTs being non-deterministic

### ISSUE THREAD

**Issue by suryakunala** [tree-sitter/tree-sitter-java#143]
### Problem description
Hi,
I just wanted to confirm whether the Trees are deterministic or not.
I have written a module to get the Code Base Graph which builds the Data Flow and Control Flow across the code base (repository). Lately, I have noticed that I'm failing to reproduce the ASTs which causing me the reproducibility issue in my Code Base Graph.
Also, my AST versioning is failing due to this.
I'm sure this issue is with specific node types.
Do someone also facing the same issue?

**Comment by amaanq** [comment]
error recovery is not exactly deterministic, but parsing should generally be (except when picking between conflicts)
