### ISSUE TITLE
Request the next version available in crates.io

### ISSUE THREAD

**Issue by ketkarameya** [tree-sitter/tree-sitter-java#146]
### Problem description
Request the next version available in crates.io(`0.20.1` ?)

**Comment by ketkarameya** [comment]
Ow! I see this is kinda a open problem https://github.com/tree-sitter/tree-sitter/discussions/1768 
Let me know if there is anything i can do from my end. 
I can see this https://github.com/tree-sitter/tree-sitter-java/blob/master/.github/workflows/publish_crate.yml , but i am not sure if I should try to invoke it (or even if I can if I try, I might night have those access)

**Comment by hendrikvanantwerpen** [comment]
New release is out: https://github.com/tree-sitter/tree-sitter-java/releases/tag/v0.20.2
