### ISSUE TITLE
Error when variable name is `yield`

### ISSUE THREAD

**Issue by rever1and** [tree-sitter/tree-sitter-java#152]
### Problem description

https://github.com/openjdk/jdk/blob/2d05d3545c8fe4d9e5ad3cee673fc938f84d1901/src/jdk.compiler/share/classes/com/sun/tools/javac/util/Names.java#L270

yet another example from jdk source

**Comment by aryx** [comment]
I think you could have created just one issue instead of 3; they're all the same.

**Comment by rever1and** [comment]
> 

sory for that, I don't know they are the same, as  far as I can.
