### ISSUE TITLE
Publish latest to NPM again

### ISSUE THREAD

**Issue by jrieken** [tree-sitter/tree-sitter-java#163]
Last time this grammar has been published to NPM was ~3yrs ago. Since then many improvements have been pushed but they are hard to consume. So, the ask is to publish latest and greatest to NPM

**Comment by jrieken** [comment]
@hendrikvanantwerpen @maxbrunsfeld can you help?

**Comment by hendrikvanantwerpen** [comment]
@jrieken New release is out: https://github.com/tree-sitter/tree-sitter-java/releases/tag/v0.20.2. I've also updated the workflows so NPM is automatically released alongside the crate.
