### ISSUE TITLE
Parameter parse error in multiple line method declaration.

### ISSUE THREAD

**Issue by Naplues** [tree-sitter/tree-sitter-java#165]
### Problem description
There is a bug in tree-sitter: the parsed method parameters will contain additional prefix (e.g., modifiers, return, and method name) when the method declaration spans multiple lines and these prefix appear before the character of '('

Java method:
public static void test_method(int a, double b,
char c, float d) {
.....
}

tree-sitter code:
para = comment_method_pairs["methods"]["parameters"]

### Expected parse tree output (optional)
The value of para is "(int a, double b,
char c, float d)"

### Actual parse tree output (optional)
**public static void test_method**(int a, double b,
char c, float d)

**Comment by amaanq** [comment]
This is not a good reproducer, be more exact about what the actual issue is and what you're doing (using a language binding? query bug? etc)
