### ISSUE TITLE
Java indent module does not indent properly with if conditions without curly braces

### ISSUE THREAD

**Issue by JustLinuxUser** [tree-sitter/tree-sitter-java#167]
### Problem description
When using tree-sitter indent module for java, it does not detect if/else/while... without "{}" to be indented.
I know that this is not a best coding practice, but it is a java feature, and I would like for this to work.

I know, it should be possible, in C tree sitter supports this feature.

Btw. I am a full noob, so mb this is not this project's fault, and something else, but I am using the latest nvim release on Arch, with tree-sitter-cmd, and this doesn't work properly

**Comment by amaanq** [comment]
belongs in nvim-treesitter
