### ISSUE TITLE
Disallowed statements inside class declaration get parsed as constructor declaration

### ISSUE THREAD

**Issue by AgnieszkaPiszcz** [tree-sitter/tree-sitter-java#169]
### Problem description

When parsing statements that are illegal inside class declaration (`if,` `for`, `while`) they get parsed as constructor declaration.
input:
```
class C {
	if (true) {}
}
```
### Expected parse tree output 

In this situation it should either be an error on the top level of the disallowed statement or they should be parsed correctly as `if`, `for` or `while` statements.

### Actual parse tree output
```
program [0, 0] - [3, 0]
  class_declaration [0, 0] - [2, 1]
    name: identifier [0, 6] - [0, 7]
    body: class_body [0, 8] - [2, 1]
      constructor_declaration [1, 1] - [1, 13]
        name: identifier [1, 1] - [1, 3]
        parameters: formal_parameters [1, 4] - [1, 10]
          ERROR [1, 5] - [1, 9]
            type_identifier [1, 5] - [1, 9]
        body: constructor_body [1, 11] - [1, 13]
```

**Comment by amaanq** [comment]
I don't think that makes sense, it's more about what's expected/allowed in there, and a best-guess as which one it should be is made.
