### ISSUE TITLE
Packages & imports are highlighted in as variables

### ISSUE THREAD

**Issue by asmodeus812** [tree-sitter/tree-sitter-java#177]
### Problem description
At the moment the package & imports are only recognized as variables, thus there is no way to customize the entire package import statement, without affecting the highlight of the variables

We have the following

```java
package com.package.name;
import java.util.Collections;
```

The package statement as a whole is highlighted only as @variable
The import, only `java.util.` is @variable, while `Collections` is @variable, superseded by @type

It would be great if both the package and / or import share a more granular highlight, to allow for better customization.

**Comment by amaanq** [comment]
highlights generally aren't controlled here, unless you're talking about the actual cli highlights with `tree-sitter highlight`. if so, then a PR is welcome to update the queries, but note that oftentimes this kind of stuff isn't distinguishable without some semantic info (LSPs job). But I feel like you're talking about some implementation of tree-sitter in whatever tool/app you're using, if so, then you'd have to file it with them (e.g. an editor/plugin)
