### ISSUE TITLE
Cant parse variable arguments ...

### ISSUE THREAD

**Issue by liuzhenghua** [tree-sitter/tree-sitter-java#184]
### Steps to reproduce
```
class Test{
    @SafeVarargs
    public static @Nullable <T extends PsiElement> T getPrevSiblingOfType(@Nullable PsiElement element
            , @NotNull Class<? extends T> @NotNull ... classes) {
        PsiElement run = element;
        while (run != null) {
            if (PsiTreeUtil.instanceOf(run, classes)) {
                return (T)run;
            }
            if (run instanceof PsiFile) break;
            run = run.getPrevSibling();
        }
        return null;
    }
}
```
classes param parsed as ERROR node type.

![image](https://github.com/user-attachments/assets/1bc734c2-ebfd-4788-84da-b93649651dc9)

**Comment by amaanq** [comment]
In the future, please provide *minimal* (!) code snippets as reproducers, with steps to reproduce *outside* of a 3rd party environment/tool. It costs me time to whittle the snippets down and figure out the *actual* issue, as an opaque screenshot isn't super helpful.

**Comment by liuzhenghua** [comment]
> ...

Thank you for your feedback. I appreciate the time you’ve taken to investigate the issue.

The root cause of this issue is that Treesitter cannot parse variadic arguments in Java. When using Treesitter's API to parse the provided class file, the type of the last parameter is parsed as ERROR (likely because the syntax file does not account for the ... character).

**Comment by liuzhenghua** [comment]
Here is the python code to reproduce this:
```python
_JAVA_LANG = Language(tsjava.language())
_JAVA_PARSER = Parser(_JAVA_LANG)

file_content = """
class Test{
    @SafeVarargs
    public static @Nullable <T extends PsiElement> T getPrevSiblingOfType(@Nullable PsiElement element
            , @NotNull Class<? extends T> @NotNull ... classes) {
        PsiElement run = element;
        while (run != null) {
            if (PsiTreeUtil.instanceOf(run, classes)) {
                return (T)run;
            }
            if (run instanceof PsiFile) break;
            run = run.getPrevSibling();
        }
        return null;
    }
}
"""
tree = cls._JAVA_PARSER.parse(bytes(file_content, "utf-8"))
```

You can also using tree sitter playground to reproduce this issue:
![image](https://github.com/user-attachments/assets/4c9c920b-b917-494f-ad77-8de1bf9f013f)

**Comment by amaanq** [comment]
Yeah no Python code doesn't cut it, but the playground is great to showcase an issue. A minimal reproducer would look like this:

```java
class A {
	public static void a(int @NotNull... arg) {
	}
}
```

*This* clearly shows the same error and doesn't have a bunch of other unrelated code alongside it.
