### ISSUE TITLE
Java parser locks up on large invalid input

### ISSUE THREAD

**Issue by aresler** [tree-sitter/tree-sitter-java#187]
### Steps to reproduce

Send [this file](https://github.com/bechmankevin/Risk-Map-Labeling/blob/ca9f9f30c99f53bfbc4e6b48bfe1fa827bd89fc9/map_data.java#L1) or something similar to Java parser

### Expected

I would expect tree-sitter to return an error or the string as is

### Actual

Tree-sitter locks up on string parsing using 100% of CPU. Why I think this is specific to Java parser (and not go-tree-sitter I'm using) is because it's not reproduced with other parsers, e.g. Python.

```stacktrace
goroutine 64180 gp=0x14000489180 m=21 mp=0x14000581b08 [syscall, 9 minutes]:
runtime.cgocall(0x10283841c, 0x140001fbb08)
        /Users/andrew/tools/go/src/runtime/cgocall.go:157 +0x44 fp=0x140001fbac0 sp=0x140001fba80 pc=0x102533ab4
github.com/smacker/go-tree-sitter._Cfunc_ts_parser_parse_string(0x12c808800, 0x0, 0x308030000, 0x11cec4)
        _cgo_gotypes.go:853 +0x34 fp=0x140001fbb00 sp=0x140001fbac0 pc=0x102641084
```

**Comment by amaanq** [comment]
You're parsing a 1.2MB **erroneous** file that is just data, I'm sorry but you're triggering error recovery on an insanely large file, it is *not* locked up, but rather takes a *long* time to parse. This use case is not what tree-sitter is designed for.

**Comment by aresler** [comment]
@amaanq Yes, I agree, but the invalid file is not sent to tree-sitter intentionally, it could be part of an automation. I understand it is best to implement some kind of validation to check that a file with .java extensions contains a valid java code, but it could be costly. I figured it would be reasonable for tree-sitter to avoid processing junk inputs like that.

Also, other parsers didn't show this behavior.

However, if you think it's not a bug and behaves as expected, I'm fine with closing the issue.

**Comment by amaanq** [comment]
Call `set_timeout_micros` to set how long at most parsing should take, and you won't be stuck in an infinite loop.

If you see other parsers not exhibiting the same behavior on a 2gb data file that is similarly structured to the Java one **then** it's potentially a bug w/ this parser.
