### ISSUE TITLE
An error exist in local_variable_declaration 

### ISSUE THREAD

**Issue by fatshi** [tree-sitter/tree-sitter-java#192]
```
        String str = "hello ", str1 = "world";
```
The 'local_variable_declaration' missing the first variable `str = "hello " `

**Comment by amaanq** [comment]
No clue what you mean, please file useful issues that have reproducers in the future.

![image](https://github.com/user-attachments/assets/d13b3181-adfb-4c1b-b606-14e51b718a7a)
