### ISSUE TITLE
Note: normal_class_declaration is no more

### ISSUE THREAD

**Issue by aymannadeem** [tree-sitter/tree-sitter-java#21]
Java treats enum types differently than other languages, in that the `enum` declaration defines a class (called an enum type). The spec defines `class_declaration` as a choice between `enum_declaration` and `normal_class_declaration`.  

I eliminated `normal_class_declaration` and replaced it with `class_declaration`, and made `enum_declaration` a first class `_declaration`.

**Comment by maxbrunsfeld** [comment]
This is a good setup. Just closing out stale issues to make the state of things clearer to external users.
