### ISSUE TITLE
fix wildcard parsing

### ISSUE THREAD

**Issue by aymannadeem** [tree-sitter/tree-sitter-java#24]
`? extends B` produces the following

```
(program [0, 0] - [1, 0]
  (ERROR [0, 0] - [0, 11]
    (unann_type [0, 2] - [0, 9]
      (unann_class_or_interface_type [0, 2] - [0, 9]
        (identifier [0, 2] - [0, 9])))
    (identifier [0, 10] - [0, 11])))
```

`wildcard` includes `_wildcard_bounds` which leads to `reference_type` which includes `class_or_interface_type` which includes `unann_class_or_interface_type` which includes `type_arguments` which could be either a `wildcard` or ` reference_type`

**Comment by maxbrunsfeld** [comment]
The `wildcard` test is passing now.
