### ISSUE TITLE
Java Grammar Finish Line

### ISSUE THREAD

**Issue by aymannadeem** [tree-sitter/tree-sitter-java#27]
This is a checklist of tasks that need completion in order to ship the Java grammar. Before open sourcing, I'd like to add polish ✨ and 🚢  the project for our own usage first. I'd love to get a team review and finalize documentation I've started. Official documentation provides explicit guard rails for the community and will likely make debugging more tractable.

### Goal: Parse 100% of top three repositories

While this is not a goal for open sourcing the project, having a 0% error rate would be a good achievement to come to. I'm currently parsing 44% of the files in the google/guava repository without any errors. This is likely caused by a few errors and addressing those would get us a long way. I will report back with more comprehensive performance stats once I look at the errors more closely. 

#### Parsing success rate
| Repository  | Percentage of files without errors | Pass? |
|---|---|---|
| [`google/guave`](https://github.com/google/guava)  | 44%  | :x: |
| [`ReactiveX/RxJava`](https://github.com/ReactiveX/RxJava)  | 46%  |  :x: |
| [`elastic/elasticsearch`](https://github.com/elastic/elasticsearch)  | 43%  | :x: |

[This](https://github.com/tree-sitter/tree-sitter-java/issues/26) is where I've determined what top three repositories to use.

[This](https://github.com/tree-sitter/tree-sitter-java/issues/25) is my test process.

### Checklist
- [x] Get top 3 repositories parsing ~90% of their files
- [x] Team review (would love to get feedback on parse trees and grammar structure)
- [ ] Document process for testing and error tracking
- [ ] Document parse tree style guide (prevents any ambiguity or debate around what a good parse tree looks like)
- [ ] Rewrite project history
- [ ] **Grammar refactoring tasks**:
  - [ ] Eliminate `normal_class_declaration` and `enum_class_declaration`
  - [ ] `formal_parameter` and `formal_list_parameter`
  - [ ] follow `argument_list` refactor and consolidate parenthesized expressions across the code
  - [x] `enum_declaration` vs. `normal_class_declaration`
  - [ ] `method_declarator`, `variable_declarator_list`, `variable_declarator`, `variable_declarator_id`, `variable_initializer`
  - [ ] `class_instance_creation_expression` vs `unqualified_class_instance_creation_expression`
  - [x] consolidate `class_body` and `class_body_declaration`
  - [ ] Eliminate `unann_type` in favor of a unified type hierarchy
  - [ ] `class_member_declaration` vs. `field_declaration`
  - [ ] Compare to JavaParser output and study its nodes
  - [x] Make `binary_expression` and `unary_expression` siblings
  - [ ] remove or improve messy comments

**Comment by maxbrunsfeld** [comment]
👍 We've got 100% of the `.java` files in these repos parsing successfully now.
