### ISSUE TITLE
Ironing out inconsistencies

### ISSUE THREAD

**Issue by aymannadeem** [tree-sitter/tree-sitter-java#36]
We should determine a consistent way of when we parse valid vs. invalid code. 

At present, we parse the following code outside of classes `x = 3`, but we don't parse `int x = 3` even though the latter is more "correct", given that most method declarations require parameters to have types.

We also don't parse methods and other conditional statements outside of classes.

**Comment by maxbrunsfeld** [comment]
I think we're in a good place now, where `program: $ => repeat($._statement)`, so that anything that's valid inside of a method can also occur at the top-level. This should enable good handling of Java code snippets.
