### ISSUE TITLE
Parse accessibility separately from `modifier`

### ISSUE THREAD

**Issue by rewinfrey** [tree-sitter/tree-sitter-java#38]
When we parse the following Java file:

```java
public class Example {

    public void example() { }
    
}
```

We identify `public` as `modifier`. It's possible from the position of `modifier` in the parse tree for the consumer to selectively inspect the contents, but `modifier` in the `tree-sitter-java` grammar could mean other things (e.g. `abstract`, `native`, `sychronized`, etc.) that aren't directly accessibility related.

What about treating accessibility (i.e. `public`, `protected`, and `private`) in the Java grammar as first class nodes in the parse tree?

### Suggested diff

```diff
(program [0, 0] - [5, 0]
  (class_declaration [0, 0] - [4, 1]
-- (modifier [0, 0] - [0, 6])
++ (public [0, 0] - [0, 6])
    (identifier [0, 13] - [0, 20])
    (class_body [0, 21] - [4, 1]
      (method_declaration [2, 4] - [2, 29]
--      (modifier [2, 4] - [2, 10])
++      (public [2,4] - [2,10])
        (method_header [2, 11] - [2, 25]
          (void_type [2, 11] - [2, 15])
          (method_declarator [2, 16] - [2, 25]
            (identifier [2, 16] - [2, 23])))
        (method_body [2, 26] - [2, 29]
          (block [2, 26] - [2, 29]))))))
```

**Comment by patrickt** [comment]
👍
