### ISSUE TITLE
Tree-sitter development process

### ISSUE THREAD

**Issue by sadikovi** [tree-sitter/tree-sitter-java#40]
### Problem description

I am working on tree-sitter support in `language-java` grammar package and have found a few inconsistencies related to tree-sitter parsing that I would like to address.

Could you suggest me a development workflow people use when working on patches, e.g. what files to change and how to test the code? It is not obvious from the documentation. Thanks!

**Comment by 50Wliu** [comment]
You'll make most of the changes in https://github.com/tree-sitter/tree-sitter-java/blob/master/grammar.js. Test your changes informally by using `tree-sitter parse your_test_file`, and formally through the tests in the `corpus` directory.

**Comment by sadikovi** [comment]
Thanks @50Wliu! I will try this workflow this weekend, need to fix a few things for correct highlighting.

**Comment by sadikovi** [comment]
Some links I found useful: 

https://tree-sitter.github.io/tree-sitter/creating-parsers
https://gist.github.com/Aerijo/df27228d70c633e088b0591b8857eeef
