### ISSUE TITLE
Limitations of scoped_identifier or any other recursive rules

### ISSUE THREAD

**Issue by sadikovi** [tree-sitter/tree-sitter-java#45]
### Problem description

I am working on tree-sitter support for language-java and am encountering multiple limitations related to [scoped_identifier](https://github.com/tree-sitter/tree-sitter-java/blob/master/grammar.js#L771) rule being recursive and the fact that only the immediate child combinator is supported in tree-sitter grammar (https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#syntax-highlighting), e.g. I don't know how to account for such recursion when trying to scope `marker_annotation` (see code below).

I figured I could do something like this:
```cson
'''
marker_annotation > identifier,
marker_annotation > scoped_identifier
''': 'scope'
```

But this does not allow me to highlight individual identifiers and would include some other nodes like `.`.

Would appreciate if someone could explain the idea behind `scoped_identifier` and suggest any possible workarounds or fixes, e.g. replacing `scoped_identifier` with a sequence of `identifier`s instead. Thanks!

This actually relates to PR #44, where I do just that.

### Actual parse tree output (optional)

```java
@Annotation.Option
public class B {
  // do something
}

// (program [0, 0] - [5, 0]
//   (class_declaration [0, 0] - [3, 1]
//     (modifier [0, 0] - [0, 18]
//       (marker_annotation [0, 0] - [0, 18]
//         (scoped_identifier [0, 1] - [0, 18]
//           (identifier [0, 1] - [0, 11])
//           (identifier [0, 12] - [0, 18]))))
//     (modifier [1, 0] - [1, 6])
//     (identifier [1, 13] - [1, 14])
//     (class_body [1, 15] - [3, 1]
//       (comment [2, 2] - [2, 17]))))

@Annotation.Option.Option2
public class C {
  // do something
}

// (program [0, 0] - [5, 0]
//   (class_declaration [0, 0] - [3, 1]
//     (modifier [0, 0] - [0, 26]
//       (marker_annotation [0, 0] - [0, 26]
//         (scoped_identifier [0, 1] - [0, 26]
//           (scoped_identifier [0, 1] - [0, 18]
//             (identifier [0, 1] - [0, 11])
//             (identifier [0, 12] - [0, 18]))
//           (identifier [0, 19] - [0, 26]))))
//     (modifier [1, 0] - [1, 6])
//     (identifier [1, 13] - [1, 14])
//     (class_body [1, 15] - [3, 1]
//       (comment [2, 2] - [2, 17]))))
```

**Comment by sadikovi** [comment]
@maxbrunsfeld @aymannadeem could you take a look? Thanks!

**Comment by sadikovi** [comment]
gentle ping @maxbrunsfeld @Aerijo.

**Comment by maxbrunsfeld** [comment]
> I am working on tree-sitter support for language-java

Just be aware that in general, this grammar isn't totally complete, we're not using it in production yet, and we may still make large changes to it before it's totally ready to include in Atom.

> this does not allow me to highlight individual identifiers and would include some other nodes like ..

Do you want to highlight all of the elements the same? I would think that the namespaces might want to be highlighted different from the actual Annotation class name. If you *do* want to target the namespaces, then your options are indeed limited because descendant selectors aren't supported. 

You *can* highlight the entire `marker_annotation` and just give the `.` some other scope (which we usually already do anyway).

**Comment by sadikovi** [comment]
Yes, I am aware of the project being WIP, but I have to start somewhere.
I will give it a go.

**Comment by sadikovi** [comment]
Can you release the new version of the library for me to test? Thanks.

**Comment by sadikovi** [comment]
I believe this has been mitigated somehow. I will open a PR for the method invocation part that is left.
