### ISSUE TITLE
Error getting source contents between boundaries

### ISSUE THREAD

**Issue by ghapereira** [tree-sitter/tree-sitter-java#58]
First of all, thank you all for the good work with tree-sitter-java, I am finding it a joy to work with.

I am having an issue working with tree-sitter-java (via [py-tree-sitter](https://github.com/tree-sitter/py-tree-sitter)).

I am parsing [this file](https://github.com/apache/dubbo/blob/master/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java) to extract some information, specifically methods' modifiers. This file contains a class that have 8 public methods and 3 private methods. When I test it, though, it shows only 2 private methods.

I identify visibility by looking whether the visibility node text contains the string "public", "protected" and "private", if none I consider it to be "package". Finding that one method was being incorrectly classified as "package" I printed the contents of all "visibility" nodes (explicitly adding the '\n' for visualization purposes):

```
start_byte - end_byte: |src_code_contents|

1980 - 2000: |@Override\n    public|
2070 - 2076: |public|
2146 - 2166: |@Override\n    public|
2242 - 2262: |@Override\n    public|
2323 - 2343: |@Override\n    public|
2422 - 2442: |@Override\n    public|
4091 - 4147: |@SuppressWarnings({"unchecked", "rawtypes"})\n    private|
5069 - 5076: |private|
5704 - 5711: |ivate L|
6907 - 6927: |rride\n    public Str|
```

As it can be seen, from the penultimate one the strings are shifted, in that case making me lose the "private" substring. The last one is shifted as well, but it does not lose the "public" substring.

I don't know what seems to be the problem... My first idea was some encoding bug, but after passing the file through dos2unix the problem still happened. I also am looking for problems in my code, e.g. if I was modifying the source contents
between checks and consequently messing with the indexes, but this is unlikely.

Does anyone have an idea about what can be happening?, and whether this must be an issue with tree-sitter-java or py-tree-sitter?

Thanks!

**Comment by maxbrunsfeld** [comment]
How are you picking the 'visibility node'? Also, how are you selecting the text? Just to check - the byte offsets should be used to slice a `bytes` object (not a string, because string slicing slices by *characters*, not by bytes).

**Comment by ghapereira** [comment]
Hi @maxbrunsfeld , thank you for the quick response!

From what you have said this is probably my problem; I read the file to be parsed as bytes for tree-sitter, but I store it reading as a string (with python's `read` method). Just for completeness I am posting my code anyway.

My code for getting the "visibility node" is 

```python
for class_component in node.children:
    if class_component.type == "class_body":
        for class_body_component in class_component.children:
            if class_body_component.type == "method_declaration":
               for child in class_body_component.children:
                   if child.type == "modifiers":
                       contents = self.get_node_contents(child)
```

This method `get_node_contents` is simply:
```python
def get_node_contents(self, node: Node) -> str:
     return copy.deepcopy(self._src_contents[node.start_byte : node.end_byte])
```

, with the `_src_contents` member being simply the contents of the file that was read with `read`.

But when I load it to be parsed by tree-sitter I am converting it first to bytes - `tree = self._parser.parse(bytes(self._src_contents, "utf-8"))`. Therefore, if I get into some unicode codepoint that has more than one byte of length I will get these off-by-n errors.

I will be testing this shortly and closing the issue with the solution as this is probably the problem. Hopefully this mistake can be used as documentation for any other lost souls.

Thanks again!

**Comment by ghapereira** [comment]
The solution for the issue was just as @maxbrunsfeld pointed out. I just changed my method to
```python
def get_node_contents(self, node: Node) -> str:
     return self._bytes_src_contents[node.start_byte : node.end_byte].decode("utf8")
```

and could get the text correctly.
