### ISSUE TITLE
Handling input elements differently

### ISSUE THREAD

**Issue by aymannadeem** [tree-sitter/tree-sitter-java#6]
Making a note about straying from the Java spec [hierarchy](https://docs.oracle.com/javase/specs/jls/se9/html/jls-3.html#jls-3.5). It groups keywords and identifiers in a way that isn't in line with how other tree-sitter language grammars are written.

For example:

Keyword:
(one of) 
```Java
abstract   continue   for          new         switch
assert     default    if           package     synchronized
boolean    do         goto         private     this
break      double     implements   protected   throw
byte       else       import       public      throws
case       enum       instanceof   return      transient
catch      extends    int          short       try
char       final      interface    static      void
class      finally    long         strictfp    volatile
const      float      native       super       while
_ (underscore)
```

Also groups [Tokens](https://docs.oracle.com/javase/specs/jls/se9/html/jls-3.html#jls-Token) in a way that doesn't match the structure suitable for the grammar.

**Comment by maxbrunsfeld** [comment]
@aymannadeem Can this one be closed out? I think that the way we're parsing keywords is good, but I'm open to any outstanding concerns about it.

**Comment by aymannadeem** [comment]
Sounds good!
