### ISSUE TITLE
Support non-ASCII identifiers

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-java#60]
We currently choke on 
```java
AVLKnoten fügeKnotenEin(AVLKnoten knoten, Comparable wert)
```

**Comment by aryx** [comment]
We have a similar issue with french accents: https://github.com/returntocorp/semgrep/issues/2704

**Comment by aryx** [comment]
@maxbrunsfeld is there a way to specify any unicode "letter" in tree-sitter?
See https://stackoverflow.com/questions/32417922/java-valid-identifier-from-java-language-specification

**Comment by aryx** [comment]
Can we use unicode regexps in tree-sitter as in https://stackoverflow.com/questions/45886840/javascript-regex-pattern-for-any-visible-unicode-letter-characters ?

**Comment by aryx** [comment]
I see this in tree-sitter-ruby const IDENTIFIER_CHARS = /[^\x00-\x1F\s:;`"'@$#.,|^&<=>+\-*/\\%?!~()\[\]{}]*/;
I guess to emulate unicode letters, but is there a more direct way?

**Comment by aryx** [comment]
I see this in tree-sitter-go:   unicodeLetter = /[a-zA-Zα-ωΑ-Ωµ]/,
does it also covers french accents? or just greek letters?

**Comment by aryx** [comment]
I also see this for PHP:     name: $ => /[_a-zA-Z\u00A1-\u00ff][_a-zA-Z\u00A1-\u00ff\d]*/,

**Comment by maxbrunsfeld** [comment]
We can use any unicode character class now. That was a recent addition to Tree-sitter. Probably we want `XID_Start`?

**Comment by aryx** [comment]
Excellent. Where is the documentation about it? Which version of tree-sitter-cli supported that?

**Comment by maxbrunsfeld** [comment]
I haven't written it up yet, though I need to do that soon. The ECMAScript regex syntax for these is documented [on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes). Tree-sitter only implements the more basic forms (e.g. `\p{Letter}`, `\p{Lu}`), not the key-value syntax (e.g. `\p{Script=Latin}`).

**Comment by maxbrunsfeld** [comment]
Fixed on master. I assumed that `isJavaIdentifierStart` means `_`, `$`, and characters in the `Letter` category, and `isJavaIdentifierPart` means all of these, plus any character in the `Decimal Digit Number` category.

**Comment by aryx** [comment]
Fantastic! Thx a lot.
