### ISSUE TITLE
Enable $ character in identifier names

### ISSUE THREAD

**Issue by yuanyehome** [tree-sitter/tree-sitter-java#62]
### Problem description
When I'm parsing a code with '$', for example:
```java
public class example {
    public static void main(String[] args) {
        int $123$ = 1;
        System.out.println($123$);
    }
}
```
tree-sitter will give an error. But it can be compiled in java11 in windows. So will this feature be added?

**Comment by aryx** [comment]
@maxbrunsfeld @dcreager can we merge this? We also need it in semgrep here:
https://github.com/returntocorp/semgrep/issues/2528
