### ISSUE TITLE
Wrong type assigned to attributes when preceded by namespace

### ISSUE THREAD

**Issue by eruizc-dev** [tree-sitter/tree-sitter-java#87]
### Problem description

Incorrect type assigned to attributes when you use the entire namespace.

Working with Spring you use `@Service` and it's recognized as an attribute (this is correct)

![image](https://user-images.githubusercontent.com/58179604/133937537-44e1ad93-b6f4-445e-9b84-f5e4d41c68bb.png)

But when you also set the namespace `@org.springframework.stereotype.Service` it's only recognized as variable

![image](https://user-images.githubusercontent.com/58179604/133937630-db2d88db-fd42-4aef-a80a-7668af6ba1d0.png)

I'm using nvim-treesitter and the popup you see is from nvim-treesitter playground

**Comment by amaanq** [comment]
This is a nvim-treesitter issue
