### ISSUE TITLE
Inconsistent Grammar 

### ISSUE THREAD

**Issue by asmodeus812** [tree-sitter/tree-sitter-java#96]
### Problem description
Hi. I have noticed some inconsistencies between the java grammar in treemacs' port for emacs and nvim for example here are two screens of the same code that are missing some things
![image](https://user-images.githubusercontent.com/15955811/148895530-f9faa633-9117-436b-848f-dc73f23fcf62.png)
![image](https://user-images.githubusercontent.com/15955811/148895541-9f16082c-d9da-4ca8-9649-066f5fc33922.png)

As you can see annotations are coloured as are keywords, variable usage is not coloured at all, member function calls as well. Vscode and nvim are consistent and look the same while in emacs it seems that only partial highlight is done.

**Comment by raghav-deepsource** [comment]
maybe the extensions are using different versions of tree-sitter-java?

**Comment by asmodeus812** [comment]
I dont think so, the emacs ts highlighting is no better than a plain regex from what i see.

**Comment by hcpsilva** [comment]
I believe the difference you see stems from the fact that both `emacs-tree-sitter` (using `tree-sitter-langs`) and NeoVim maintain their own `highlights.scm` file. [https://github.com/emacs-tree-sitter/tree-sitter-langs/blob/master/queries/java/highlights.scm](Here) you can see that the `highlights.scm` file used by `emacs-tree-sitter` hasn't been updated in over two years and even differs from the `queries/highlights.scm` from this repository. I also believe that the NeoVim tree-sitter maintainers further enhance their `highlights.scm` files, which could also contribute to the difference you observe.

Unfortunately, there is no escape in that, as the highlight tags used in this repo, in the Emacs highlighter and the NeoVim highlighter naturally differ (the names may differ, NeoVim could have more highlighting tags, etc). That way, it's hard to contribute to the original grammar repository any enhancements to the highlighting queries that any one of these editors make.

Of course, there are similarities between the highlighting tags, but the process is manual and the maintainers do this for free on their spare time. If you feel inclined, I'd suggest you take a look at the highlighting queries made by NeoVim and then replicate those to the Emacs implementation, following the stylistic patterns from the other highlighting queries in the implementation.
